### ISSUE TITLE
Adavanced search by Member not working with 2.1b2

### ISSUE THREAD

**Issue by meshugy** [bauerjj/SphinxSearch#13]
The "Posted by Member" field in the advanced search function seems to be totally ignored by the plugin. When I enter a member's user name, it has no bearing on the search results. I've tried all three search types (any, all, and extended) with no luck. If I search in extended mode using the operator @user it works perfectly.

**Comment by mcuhq** [comment]
@meshugy Is this still the case?

**Comment by meshugy** [comment]
@mcuhq yes, it still ignores the "Posted by Member" field.
thanks!

**Comment by mcuhq** [comment]
Alright I have some time to look at it again
