### ISSUE TITLE
GDN_sph_stats.keywords_full is not populated

### ISSUE THREAD

**Issue by kenston** [bauerjj/SphinxSearch#28]
In my new installation of the plugin (20190101), the DB structure for `GDN_sph_stats` is:
| Field         | Type         | Null | Key | Default | Extra          |
|---------------|--------------|------|-----|---------|----------------|
| id            | int(11)      | NO   | PRI |         | auto_increment |
| mode          | int(11)      | NO   |     |         |                |
| keywords      | varchar(255) | NO   | MUL |         |                |
| keywords_full | varchar(255) | NO  |     |         |                |
| date_added    | datetime     | NO   |     |         |                |

However, whenever I conduct a search, I'm encountering the following error:
```
PHP message: PHP Fatal error:  Field 'keywords_full' doesn't have a default value|Gdn_Database|Query|insert `GDN_sph_stats` 
(`keywords`, `mode`, `date_added`) 
```

My current workaround is to alter the DB structure to allow `keywords_full`  to have NULL values.

It seems that in `class.widgets.stats.php`, `keywords_full` isn't included:
```
        foreach ($Words as $Word => $Info) {
            $Query.=$Word . ' ';
            Gdn::SQL()
                    ->Insert('sph_stats', array('keywords' => $Word, 'mode' => 1, 'date_added' => Gdn_Format::ToDateTime())); //mode == 1 means plain word
        }
        Gdn::SQL()
                ->Insert('sph_stats', array('keywords' => $Query, 'mode' => 2, 'date_added' => Gdn_Format::ToDateTime())); //mode == 2 means hwole query
    }
```

**Comment by bauerjj** [comment]
Thanks! Do you mind issuing a PR with that DB structure fixed? Does the plugin work well otherwise? I haven't used it in a while.

**Comment by kenston** [comment]
> Do you mind issuing a PR with that DB structure fixed?

Sure. Is the correct fix to remove `keywords_full` when creating the table?

> Does the plugin work well otherwise?

The plugin still works well with the latest Vanilla 3.3.

**Comment by bauerjj** [comment]
> Sure. Is the correct fix to remove keywords_full when creating the table?

Just make this boolean a `TRUE` https://github.com/bauerjj/SphinxSearch/blob/1a4e5c0c39125a96f394908ea367188c22fd65be/class.sphinxsearch.plugin.php#L709

Good to hear it still works!
